### ISSUE TITLE
'find' won't indicate "whether an array of numbers contains any odd values."

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/phase-1-array-element-finding#1]
### Canvas Link

https://learning.flatironschool.com/courses/5185/pages/finding-array-elements?module_item_id=396137

### Concern

Array.prototype.find() says:
"Say we want to determine whether an array of numbers contains any odd values. We can write the following callback function to do this:"

But the callback function won't do this. It will only find one such odd value, i.e. it will not say if there are multiple odd values.

### Suggested Changes

How about:
Say we want to determine whether an array of numbers contains an odd value.

Side benefit: Might help jar the reader into seeing that 'find' will only return one element, despite having a whole array of elements providing raw material.

**Comment by lizbur10** [comment]
Hi again @brigj1! I'm going to have to disagree with you on this one. The relevant definition of "any" (according to Merriam Webster) is "one or more", not "more than one". Furthermore, I'm afraid that if students read "...whether an array of numbers contains an odd value", they might misinterpret it in the opposite way and think **one** odd value, which `find` won't tell them - it returns the first one found, but there could be more.

Thanks as always for contributing 💙
